In [2]:
import cv2
import numpy as np

In [29]:
img = cv2.imread("input\River.jpg")
imS = cv2.resize(img, (250, 250)) 
cv2.imshow("image",imS)
cv2.waitKey(0)

-1

In [45]:
ma = np.ones((3,3),np.float32)/9
smooth = cv2.filter2D(img,-1,ma)
smooth1 = cv2.filter2D(smooth,-1,ma)
sm = cv2.resize(smooth1, (250, 250)) 
cv2.imshow("image111",sm)

m1 = np.matmul(ma,ma)
smooth2 = cv2.filter2D(img,-1,m1)
sm2 = cv2.resize(smooth2, (250, 250)) 
cv2.imshow("image222",sm2)

m2 = np.dot(ma,ma)/(ma+ma)
smooth3 = cv2.filter2D(img,-1,m2)
sm3 = cv2.resize(smooth3, (250, 250)) 
cv2.imshow("image333",sm3)
cv2.waitKey(0)

-1

In [42]:
print(img[0][0])

print(smooth[0][0])

print(smooth1[0][0])

print(smooth2[0][0])

print(smooth3[0][0])

[1 0 4]
[142 142 145]
[122 123 126]
[47 47 48]
[255 255 255]
